jobs:
  - name: get_latest_image_list
    type: runSh
    steps:
      # This will automatically set the environment variables needed by rancher-compose
      - IN: pull_release_trigger
      - IN: gcloud_config
      - TASK:
        - script: |
            gcloud container images list --format="json" --repository=gcr.io/kubernetes-helm |jq .[].name |sed 's/"//g'> repolist
            gcloud container images list --format="json" --repository=gcr.io/google-containers |jq .[].name |sed 's/"//g'>> repolist

            cat repolist | while read repo
            do \
            version=$(gcloud container images list-tags --format 'get(tags)' --limit=1 $repo) 
            IFS=';' read -a tags <<< $version
            for tag in ${tags[@]}
            do \
              echo "$repo" "$tag" >> imagelist
              echo "$repo" "$tag"
            done 
            done
            shipctl copy_file_to_state "imagelist"

  - name: push_new_image
    type: runSh
    steps:
      - IN: qingcloud_hub_config
      - IN: get_latest_image_list
      - TASK:
        - script: |
            imageliststate=$(shipctl get_resource_state get_latest_image_list)
            cp $imageliststate/imagelist newimagelist
            cat newimagelist | while read item 
            do \
            repo=$(echo $item|awk '{ print $1}')
            tag=$(echo $item| awk '{ print $2}')
            project=${repo#gcr.io/}
            project=${project//-/_}
            (docker pull $repo:$tag && docker tag $repo:$tag dockerhub.qingcloud.com/$project:$tag &&  docker push dockerhub.qingcloud.com/$project:$tag && echo "pushed $repo:$tag to dockerhub.qingcloud.com/$project:$tag")|| true
            done
    on_success:
      - script: echo "Synced $VERSION to bucket"
      - NOTIFY: slack
    on_failure:
      - script: echo "Failed to get latest build $VERSION"
      - NOTIFY: slack
    on_cancel:
      - script: echo "Get latest build $VERSION canceled"
      - NOTIFY: slack
